import os


POSTGRES_HOST = os.environ["POSTGRES_HOST"]
POSTGRES_PORT = os.environ["POSTGRES_PORT"]
POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_DB_NAME = os.environ["POSTGRES_DB_NAME"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
